name: release tar

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: make archive
        run: |
          tar czvf data.tar.gz data

      - name: upload archive
        uses: actions/upload-artifact@v4
        with:
          path: data.tar.gz

